<a href="https://colab.research.google.com/github/parksuejin1026/sophomore_2ndTerm/blob/main/DeepLearning/hw2_%EB%B0%95%EC%88%98%EC%A7%84_20251285.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
print(f"PyTorch version: {torch.__version__}")

PyTorch version: 2.9.0+cpu


In [3]:
s = torch.tensor(25)
v = torch.tensor([90, 85, 70])
m = torch.tensor([[90, 85, 70], [70, 75, 88]])
t = torch.tensor([[[1, 2], [3,4]], [[5,6], [7,8]]])

for name, x in [('scalar', s), ('vector', v), ('matrix', m), ('tensor', t)]:
  print(name, 'dim = ', x.dim(), 'shape = ', tuple(x.shape), 'numel = ', x.numel())

scalar dim =  0 shape =  () numel =  1
vector dim =  1 shape =  (3,) numel =  3
matrix dim =  2 shape =  (2, 3) numel =  6
tensor dim =  3 shape =  (2, 2, 2) numel =  8


In [12]:
# 예제 1-1
ex1 = torch.tensor([1, 2, 3, 4, 5])
print('예제 1-1. 숫자 5개 Vector 만들기')
print(f"Vector : {ex1} \n")
# 예제 1-2
print("예제 1-2. (2,3,4) Tensor 만들기")
ex2 = torch.tensor([[[1,2,3,4], [5,6,7,8], [9,10,11,12]],[[13,14,15,16],[17,18,19,20],[21,22,23,24]]])
print("Tensor Shape : ", tuple(ex2.shape),"\n")
# 예제 1-3
print("예제 1-3. 전체 원소 수 확인")
print("전체 원소 수는 : ", ex2.numel(), "개!\n")
# 예제 1-4
print("예제 1-4. (32, 3, 224, 224)가 어떤 데이터인지 설명")
print("224 x 224 크기의 컬러 (RGB) 이미지 32장으로 이루어진 Batch")

예제 1-1. 숫자 5개 Vector 만들기
Vector : tensor([1, 2, 3, 4, 5]) 

예제 1-2. (2,3,4) Tensor 만들기
Tensor Shape :  (2, 3, 4) 

예제 1-3. 전체 원소 수 확인
전체 원소 수는 :  24 개!

예제 1-4. (32, 3, 224, 224)가 어떤 데이터인지 설명
224 x 224 크기의 컬러 (RGB) 이미지 32장으로 이루어진 Batch


In [5]:
# 실습 2
print("실습 2. (32, 3, 224, 224)에서 각 숫자가 무엇을 의미하는지 설명하세요.")
print("32 : 32장의 이미지, 3 : RGB 3개의 색깔, 224 : 세로축 224 픽셀, 224 : 가로축 224 픽셀")

실습 2. (32, 3, 224, 224)에서 각 숫자가 무엇을 의미하는지 설명하세요.
32 : 32장의 이미지, 3 : RGB 3개의 색깔, 224 : 세로축 224 픽셀, 224 : 가로축 224 픽셀


In [6]:
# 실습 3
torch.manual_seed(0)
scores = torch.randint(50, 101, (30, 3))
print(scores.shape)
print(scores[:5])

torch.Size([30, 3])
tensor([[ 91,  53,  79],
        [ 83,  69,  50],
        [ 66,  60,  90],
        [ 89, 100,  94],
        [ 80,  59,  75]])


In [7]:
# 실습 3
print('1번 학생 : ', scores[0])
print('전체 학생의 첫 과목 점수 :', scores[:,0])
print('1번 학생의 두 번째 과목 점수 : ', scores[0,1])
print('마지막 학생의 점수 : ', scores[-1])

1번 학생 :  tensor([91, 53, 79])
전체 학생의 첫 과목 점수 : tensor([ 91,  83,  66,  89,  80,  91, 100,  94,  76,  58,  84,  83,  66,  51,
         72,  73,  97,  97,  76,  93,  87,  77,  78,  63,  92,  85,  54,  52,
         77,  69])
1번 학생의 두 번째 과목 점수 :  tensor(53)
마지막 학생의 점수 :  tensor([69, 81, 61])


In [8]:
# 실습 3
print("예제 3-1. 10~20번째 학생의 첫 번째 과목 점수")
print(f"{scores[9:20 ,0]}")
print("예제 3-2. 전체 학생의 세 번쨰 과목")
print(f"{scores[:,2]}")
print("예제 3-3. 앞 10명의 두 번째 과목")
print(f"{scores[:10, 1]}")
print("예제 3-4. 마지막 3명의 전체 점수")
print(f"{scores[-3:, :]}")

예제 3-1. 10~20번째 학생의 첫 번째 과목 점수
tensor([58, 84, 83, 66, 51, 72, 73, 97, 97, 76, 93])
예제 3-2. 전체 학생의 세 번쨰 과목
tensor([ 79,  50,  90,  94,  75,  56,  67,  55,  57,  98,  70,  71, 100,  71,
         66,  75,  63,  81,  73,  97,  89,  52,  85,  70,  74,  96,  58,  57,
         69,  61])
예제 3-3. 앞 10명의 두 번째 과목
tensor([ 53,  69,  60, 100,  59,  53,  95,  82,  52,  95])
예제 3-4. 마지막 3명의 전체 점수
tensor([[52, 79, 57],
        [77, 64, 69],
        [69, 81, 61]])


In [9]:
# 실습 4
print('현재 dtype : ', scores.dtype)
scores_f = scores.float()
print(f"변환 후 : {scores_f.dtype}")
print(f"평균 : {scores_f.mean()}")

현재 dtype :  torch.int64
변환 후 : torch.float32
평균 : 74.94444274902344


In [10]:
# 실습 5
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
x = scores_f.to(device)
print(f"device : {device}")
print(f"tensor device : {x.device}")

device : cpu
tensor device : cpu


In [13]:
# 실습 6
x = torch.arange(12)
print(x.reshape(3,4))
print(x.reshape(2,6))
print(x.reshape(2,-1))

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])
tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])


In [14]:
# 실습 6
print("실습 6. (24,)을 (2,12), (3,8), (4,6), (5,5)로 바꿀 수 있는가?")
print("(2, 12), (3, 8), (4, 6)은 전체 원소 개수 24개로 가능하지만, (5, 5)는 25개라 불가능")

실습 6. (24,)을 (2,12), (3,8), (4,6), (5,5)로 바꿀 수 있는가?
(2, 12), (3, 8), (4, 6)은 전체 원소 개수 24개로 가능하지만, (5, 5)는 25개라 불가능


In [15]:
# 실습 7
a = torch.tensor([[1., 2.], [3., 4.]])
b = torch.tensor([[10., 20.], [30., 40.]])

print(f"a * b = \n {a*b}")
print(f"a @ b = \n {a@b}")

a * b = 
 tensor([[ 10.,  40.],
        [ 90., 160.]])
a @ b = 
 tensor([[ 70., 100.],
        [150., 220.]])


In [16]:
# 실습 8
scores = scores.float()
bonus = torch.tensor([5., 0., 10.])

print(f'과목별 평균 : {scores.mean(dim = 0)}')
print(f'학생별 평균 shape : {scores.mean(dim = 1).shape}')
print(f'전체 +5 shape : {(scores + 5).shape}')
print(f'과목별 bonus shape : {(scores+bonus).shape}')

과목별 평균 : tensor([78.4667, 73.0667, 73.3000])
학생별 평균 shape : torch.Size([30])
전체 +5 shape : torch.Size([30, 3])
과목별 bonus shape : torch.Size([30, 3])
